#!/bin/sh
[ -d ~/.i3 ] || mkdir  ~/.i3

[ -d ~/.vim/bundle/Vundle.vim ] || git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

[ -d ~/.oh-my-zsh ] || git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh 

[ -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ] || git clone git://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting 

[ -d ~/.vimperator/colors ] || git clone https://github.com/vimpr/vimperator-colors.git ~/.vimperator/colors

chmod +x i3/conky
ln -sf $(pwd)/i3/config ~/.i3/config
ln -sf $(pwd)/i3/conky ~/.i3/conky
ln -sf $(pwd)/i3/conkyrc ~/.i3/conkyrc
ln -sf $(pwd)/vimrc ~/.vimrc
ln -sf $(pwd)/zshrc ~/.zshrc
ln -sf $(pwd)/tmux.conf ~/.tmux.conf
ln -sf $(pwd)/Xresources ~/.Xresources 
ln -sf $(pwd)/vimperatorrc ~/.vimperatorrc
ln -sf $(pwd)/custom.zsh-theme ~/.oh-my-zsh/themes/custom.zsh-theme
ln -sf $(pwd)/xinitrc ~/.xinitrc
ln -sf $(pwd)/compton.conf ~/.config/compton.conf

vim +PluginInstall! +PluginClean +qall

source ~/.zshrc

git clone https://github.com/powerline/fonts.git
exec ./fonts/install.sh &
wait $!
rm -rf fonts
