#!/bin/sh
# Req: nvim, kitty, ripgrep, fnm, tmux, fzf

[ -d ~/.config ] || mkdir ~/.config
[ -d ~/.oh-my-zsh ] || git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
[ -d ~/.tmux/plugins/tpm ] || git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

ln -sf $(pwd)/zsh/zshrc ~/.zshrc

ln -sf $(pwd)/config/gitconfig ~/.gitconfig
ln -sf $(pwd)/config/gitignore_global ~/.gitignore_global
ln -sf $(pwd)/config/gitconfig-work ~/.gitconfig-work
ln -sf $(pwd)/config/tmux ~/.tmux.conf
ln -sf $(pwd)/config/starship ~/.config/starship.toml
ln -sf $(pwd)/config/ripgrep.ignore ~/.ignore

if [ -d ~/.config/nvim/lua/plugins ]; then
  for f in $(pwd)/nvim/plugins/*.lua; do
    ln -sf "$f" ~/.config/nvim/lua/plugins/"$(basename "$f")"
  done
fi
