#!/bin/sh

#i3wm configs
[ -d ~/.i3 ] || mkdir  ~/.i3

chmod +x i3/conky
ln -sf $(pwd)/i3/config ~/.i3/config
ln -sf $(pwd)/i3/conky ~/.i3/conky
ln -sf $(pwd)/i3/conkyrc ~/.i3/conkyrc

#vim configs
[ -d ~/.vim/bundle/Vundle.vim ] || git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

ln -sf $(pwd)/vim/vimrc ~/.vimrc
vim +PluginInstall! +PluginClean +qall

#ZSH configs
[ -d ~/.oh-my-zsh ] || git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh 
[ -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ] || git clone git://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting 

ln -sf $(pwd)/zshrc ~/.zshrc
ln -sf $(pwd)/custom.zsh-theme ~/.oh-my-zsh/themes/custom.zsh-theme
source ~/.zshrc

#vimperator configs
[ -d ~/.vimperator/colors ] || git clone https://github.com/vimpr/vimperator-colors.git ~/.vimperator/colors
ln -sf $(pwd)/vimperatorrc ~/.vimperatorrc

#X configs
ln -sf $(pwd)/Xresources ~/.Xresources 
ln -sf $(pwd)/xinitrc ~/.xinitrc
ln -sf $(pwd)/compton.conf ~/.config/compton.conf

ln -sf $(pwd)/tmux.conf ~/.tmux.conf


git clone https://github.com/powerline/fonts.git
exec ./fonts/install.sh &
wait $!
rm -rf fonts
