set nocompatible
filetype off

set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/
"
call plug#begin()

	Plug 'ctrlpvim/ctrlp.vim'
	Plug 'digitaltoad/vim-pug', {'for': 'jade'}
	Plug 'editorconfig/editorconfig-vim'
	Plug 'honza/vim-snippets'
	Plug 'jelera/vim-javascript-syntax', {'for': 'javascript'}
	Plug 'keith/rspec.vim', {'for': 'ruby'}
	Plug 'mileszs/ack.vim'
	Plug 'raimondi/delimitmate'
	Plug 'ryanoasis/vim-devicons', {'on': 'NERDTreeToggle'}
	Plug 'scrooloose/nerdcommenter'
	Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'}
	Plug 'scrooloose/syntastic'
	Plug 'sirver/ultisnips'
	Plug 'tpope/vim-haml', {'for': 'haml'}
	Plug 'tpope/vim-markdown', {'for': 'markdown'}
	Plug 'tpope/vim-rails', {'for': 'ruby'}
	Plug 'tpope/vim-repeat'
	Plug 'tpope/vim-surround'
	Plug 'vim-airline/vim-airline'
	Plug 'Valloric/YouCompleteMe', { 'do': './install.py --clang-completer' }

call plug#end()

filetype plugin indent on

autocmd BufNewFile,BufReadPost *.md set filetype=markdown
autocmd BufNewFile,BufReadPost *.tex set filetype=tex

let g:syntastic_auto_loc_list=1
let g:syntastic_enable_signs=1
let g:syntastic_quiet_messages = {'level': 'warnings'}
let g:syntastic_check_on_open=1

let g:airline_powerline_fonts = 1

let g:ycm_add_preview_to_completeopt=0
let g:ycm_confirm_extra_conf=0
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']

let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>""

set completeopt-=preview

let mapleader = ','

map <leader>n :NERDTreeToggle<CR>
map <leader>q :q<cr>
map <leader>s :sh<cr>
map <leader>w :w!<cr>
map <space> /

map <C-c> <CR><Esc>O

set ai
set shiftwidth=4
set laststatus=2
set list
set listchars=trail:·,eol:↲,tab:»\ 
set tabstop=4
set shiftround
set nosmartindent
set noexpandtab

set clipboard=unnamedplus
set ignorecase
set incsearch
set magic
set number
set ruler
set smartcase
set splitbelow
set splitright
set wildignore=*.o,*.obj,*~
set wildmenu
set ls=2

syntax on
"gvim stuff
set guioptions-=m "remove menu bar
set guioptions-=T "remove tool bar
set guioptions-=r "remove right hand scroll bar
set guioptions-=L "remove left hand scroll bar
