export ZSH=$HOME/.oh-my-zsh

plugins=(archlinux git npm yarn tmuxinator fzf extract nvm)

export TERM="xterm-256color"
export EDITOR="/usr/bin/nvim"

source $ZSH/oh-my-zsh.sh

alias cat=bat
alias vim=nvim
alias vi=nvim

export PATH

zstyle ':completion:*' rehash true

if [ -f /usr/share/nvm/init-nvm.sh ]
then
	source /usr/share/nvm/init-nvm.sh
else
	export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi

eval "$(starship init zsh)"

if command -v mkcert &> /dev/null
then
	export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
	export NODE_OPTIONS=--max_old_space_size=8192
fi

if command -v pnpm &> /dev/null
then
	export PNPM_HOME="/home/diego/.local/share/pnpm"
	case ":$PATH:" in
  	*":$PNPM_HOME:"*) ;;
  	*) export PATH="$PNPM_HOME:$PATH" ;;
	esac
fi
# pnpm
# pnpm end
