export ZSH=$HOME/.oh-my-zsh

plugins=(archlinux git npm yarn tmuxinator fzf extract nvm)

export TERM="xterm-256color"
export EDITOR="/usr/bin/vim"

source $ZSH/oh-my-zsh.sh

alias cat=bat

export PATH

zstyle ':completion:*' rehash true

if [ -f /usr/share/nvm/init-nvm.sh ]
then
	source /usr/share/nvm/init-nvm.sh
else
	export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi

eval "$(starship init zsh)"
