export ZSH=$HOME/.oh-my-zsh

plugins=(archlinux git npm yarn tmuxinator fzf extract)

export TERM="xterm-256color"
export EDITOR="/usr/bin/vim"

source $ZSH/oh-my-zsh.sh

alias cat=bat

export PATH

zstyle ':completion:*' rehash true
eval "$(starship init zsh)"
